### ISSUE TITLE
Unofficial vyos logo question

### ISSUE THREAD

**Issue by marekm72** [onedr0p/vyos-config#1]
This is a question about the "unofficial-builds-for-vyos" project but that repo is archived read-only so asking here.
There is a current project with detailed instructions and automated scripts (and backed up elsewhere in case it ever disappears from here) to make it reasonably easy to build 1.3 and 1.4 LTS-like images - see https://github.com/dd010101/vyos-jenkins/
Can the image from https://github.com/onedr0p/unofficial-builds-for-vyos/issues/134#issuecomment-2067514259 be used as replacement for the official one in the self-built images?  What is the copyright of this image?

**Comment by onedr0p** [comment]
It is AI generated, so probably no copyright exists, with that said I forgot this repo exists and will archive it.

Feel free to join our Discord to discuss further.

https://discord.gg/home-operations
